### PR TITLE
Pull quote block

### LINKED ISSUE #22: Choose pull quotes for Developers page (2).
- [ ] Choose 10–25 words of praise or review from two reviews
- [ ] Provide citation (name, source link, publication)

If possible, it would be great to include an avatar or publication logo. See #21 for discussion about legality of doing so.

### LINKED ISSUE #23: Choose pull quotes for Service Integrators page (2).
- [ ] Choose 10–25 words of praise or review from two reviews
- [ ] Provide citation (name, source link, publication)

If possible, it would be great to include an avatar or publication logo. See #21 for discussion about legality of doing so.

### LINKED ISSUE #24: Choose pull quotes for Contributors page (2).
- [ ] Choose 10–25 words of praise or review from two reviews
- [ ] Provide citation (name, source link, publication)

If possible, it would be great to include an avatar or publication logo. See #21 for discussion about legality of doing so.

### PR DESCRIPTION
**Pull request by jlengstorf**
Added a new pull quote block, including a fading mechanism to move between the quotes.

This also adds JavaScript bundling capabilities via https://github.com/rollup/rollup. No changes to the dev flow, but **this does add a dependency on [npm](https://www.npmjs.com/) for local development.**

fixes #22 
fixes #23 
fixes #24

### CODE REVIEW

**Comment by krook** [comment]
Looks good to me. One concern might be around the non-ASCII double quotes on the pullquotes, let's see how that works out for them Cotton.

**Comment by jlengstorf** [comment]
@krook Do we have to support browsers old enough to break with non-ASCII characters? It's easy enough to swap out for HTML entities — I just... didn't realize that was still a thing. :)

**Comment by krook** [comment]
@jlengstorf Back in my day we used to have to support Netscape 4.5. We encoded everything with entities. Even spaces. And single pix clear GIFs.

**Comment by krook** [comment]
@jlengstorf But seriously, I defer to you on what the browser support is. I just didn't know if some people with modern browsers would have issues and see question marks inside of black diamonds.

**Pull request merged**
