### PR TITLE
Add new sticker design submitted by IBM

### PR DESCRIPTION
**Pull request by csantanapr**

### CODE REVIEW

**Comment by bjustin-ibm** [comment]
@csantanapr Is it possible to get this in SVG format? SVG is, I believe, the most flexible format for future use (printing, modifications, etc.).

**Comment by csantanapr** [comment]
That's what they submitted to Apache, I can try asking then to see if they can send an SVG

**Comment by csantanapr** [comment]
@bjustin-ibm sent an email requesting SVG, let's see if we hear back.

**Comment by csantanapr** [comment]
Never heard back, no SVG 👎

**Comment by csantanapr** [comment]
converted pdf to png, at least it's something

**Pull request merged**
